# Generated by Django 4.0.2 on 2022-03-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('list_id', models.IntegerField()),
                ('user', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('list_id', models.IntegerField()),
                ('user', models.CharField(max_length=64)),
                ('posting_time', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_name', models.CharField(max_length=64)),
                ('it_desc', models.CharField(max_length=1000)),
                ('it_seller', models.CharField(max_length=64)),
                ('bid_winner', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('category', models.CharField(max_length=64)),
                ('starting_bid', models.IntegerField()),
                ('img_url', models.URLField(blank=True, default=None, max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watcher', models.CharField(max_length=64)),
                ('list_id', models.IntegerField()),
            ],
        ),
    ]
