# Generated by Django 4.0.2 on 2022-03-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_categories_comments_listings_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='current_bid',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='listings',
            name='it_desc',
            field=models.CharField(max_length=100),
        ),
    ]
