# Generated by Django 4.0.2 on 2022-03-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_current_bid_alter_listings_it_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='current_bid',
            field=models.IntegerField(),
        ),
    ]
