# Generated by Django 4.0.2 on 2022-03-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listings_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='current_bid',
        ),
    ]
