# Generated by Django 4.0.2 on 2022-03-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listings_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='current_bid',
            field=models.IntegerField(default=None),
        ),
    ]
